Add support for building NCER files with OAM count > 1
red031000/nitrogfx pull request #11
Opened 2024-10-17 16:16 UTC by joshua-smith-12

the KBEC size is currently calculated using `options->cellCount * (options->extended ? 0x16 : 0xe)`, which assumes each cell contains only 1 OAM (OAM size = 0x06, bank size = 0x10 or 0x08)

ensure we calculate the right size by adding 0x06 for each OAM in the cell

2024-10-19 02:41 UTC, red031000 commented
this + your other PRs are very difficult to properly review without the NCER/NANR files that are causing the issues expicitly listed, please could you link them to me on discord (not in #pokeplatinum please) so I can take a look and properly review them

2024-10-19 22:58 UTC, red031000 commented
just checked, the "partition data" you references is infact VRAM transfer data, there's an option issue for it in #1 with some documentation on the format, you can have a go at implementing it if you wish with that documented format, or using the G2D docs for it, but I'm happy to implement it myself if you wish, given it's come up now

2024-10-20 02:20 UTC, joshua-smith-12 commented
Thanks! I will take a stab at implementing that in the next couple of days

2024-10-20 17:59 UTC, joshua-smith-12 commented on gfx.c
> +        // read 1 VRAM transfer data block for each cell (this is an assumption based on the NCERs I looked at)
only thing I wanted to note on this is this part, the G2d spec indicates `pCellTransferDataArray` is an array (clear from the name) but does not specify the size or if there's 1 element per cell. i made an assumption for this

2024-10-27 05:03 UTC, red031000 requested changes
I think it would be a good idea to add something when parsing a json if the field does not exist it adds it to the json with a default value, cause at the moment it'll default to false, but it's good to have a unified standard

2024-10-27 05:03 UTC, red031000 commented on gfx.c
> +            options->transferData[idx] = malloc(sizeof(struct CellVramTransferData));
malloced but not freed, same as above

2024-10-27 05:03 UTC, red031000 commented
(note the only thing that strictly needs to be addressed is the malloc, adding the json writes if field is missing isn't a priority

2024-10-28 00:20 UTC, red031000 approved these changes

2024-10-28 00:20 UTC, merged