update NANR parser to handle resultType better and handle padding
red031000/nitrogfx pull request #14
Opened 2024-10-20 17:57 UTC by joshua-smith-12

moved the changes from #13 into the existing NANR processing routines. main changes are listed below:

- determine the resultType field for each animationResult from the type of the sequence instead of inferring from the data layout
- properly apply 0xCCCC padding where required (only when the results for a sequence are not 4-byte aligned)

also 1 likely breaking change which will need to be reviewed on how to handle:

- remove `animationElement` field in SequenceData, read `animationType` from the location this was coming from

(the G2d spec actually states `animationType` is a u32 at this location, but from testing against real NANR files, it's apparent `animationType` is only the first 2 bytes of this field + the second half of the field is used for something else undocumented)

i opted to rename the JSON fields for this (`animationElement` -> `animationType`, `animationType` -> `animationType2`) which would be breaking for existing files. it would be easy (but maybe confusing to maintain) to just keep the existing names and use `animationElement` for the type for each result.

2024-10-27 05:13 UTC, red031000 commented
I'm not 100% on why you decided to rename animationElement to animationType?
the g2d spec is kinda clear on this one actually, the lower 16 bytes are of type NNSG2dAnimationElement, and the upper 16 bytes are of type NNSG2dAnimationType
the enums are defined as follows
```
typedef enum NNSG2dAnimationElement
{
    NNS_G2D_ANIMELEMENT_INDEX = 0x0, // Index only
    NNS_G2D_ANIMELEMENT_INDEX_SRT , // Index + SRT
    NNS_G2D_ANIMELEMENT_MAX
}
NNSG2dAnimationElement;
```
and
```
typedef enum NNSG2dAnimationType
{
    NNS_G2D_ANIMATIONTYPE_INVALID = 0x0, // Illegal type
    NNS_G2D_ANIMATIONTYPE_CELL , // Cell
    NNS_G2D_ANIMATIONTYPE_MULTICELLLOCATION , // MultiCell
    NNS_G2D_ANIMATIONTYPE_MAX
}
NNSG2dAnimationType;
```
as such it's fine as is? so I am somewhat confused

2024-10-27 23:46 UTC, joshua-smith-12 commented
oh whoops, thanks! I think I didn't read that part of the spec properly... I will adjust it back, the parsing changes should still be valid but should be based on `animationElement`. (i'll send over a couple NANRs to test against as well)

2024-10-28 00:26 UTC, red031000 commented on gfx.c
> +    int *usedResults = malloc(sizeof(int) * options->frameCount);
malloc without free

2024-10-28 00:26 UTC, red031000 requested changes
whoops I was supposed to put that in a request changes not as a single comment

2024-11-09 17:53 UTC, merged